baseURL = "http://localhost:1313/"
languageCode = "tr-TR"
title = "Genel Cerrahi Dersleri"
#theme = "adanacerrahitheme"
#theme = "hugo-theme-gallery-main"
theme = "ananke"

[params]
  author = "Ed"
  description = "4. sınıf öğrencileri için Genel Cerrahi ders portalı"

[[menu.main]]
  name = "1 - Travma - Acil Cerrahi"
  url = "/posts/travma/"
  weight = 1

[[menu.main]]
  name = "2 - Batın Cerrahi"
  url = "/posts/2-batin-cerrahisi/"
  weight = 2

[[menu.main]]
  name = "3 - Özelleşmiş Cerrahi"
  url = "/posts/3-ozellesmis-cerrahi/"
  weight = 3
 
